config/routes.rb
MyDemo::Application.routes.draw do
  resources :randomtessses

  resources :yahooposts

  resources :sinaposts

  resources :microposts

  resources :users

  get "welcome/index"

  root :to => "welcome#index"

end

app/models/yahoopost.rb
class Yahoopost < ActiveRecord::Base
end

app/controllers/yahooposts_controller.rb
class YahoopostsController < ApplicationController
  # GET /yahooposts
  # GET /yahooposts.xml
  def index
    @yahooposts = Yahoopost.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @yahooposts }
    end
  end

  # GET /yahooposts/1
  # GET /yahooposts/1.xml
  def show
    @yahoopost = Yahoopost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @yahoopost }
    end
  end

  # GET /yahooposts/new
  # GET /yahooposts/new.xml
  def new
    @yahoopost = Yahoopost.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @yahoopost }
    end
  end

  # GET /yahooposts/1/edit
  def edit
    @yahoopost = Yahoopost.find(params[:id])
  end

  # POST /yahooposts
  # POST /yahooposts.xml
  def create
    @yahoopost = Yahoopost.new(params[:yahoopost])

    respond_to do |format|
      if @yahoopost.save
        format.html { redirect_to(@yahoopost, :notice => 'Yahoopost was successfully created.') }
        format.xml  { render :xml => @yahoopost, :status => :created, :location => @yahoopost }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @yahoopost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /yahooposts/1
  # PUT /yahooposts/1.xml
  def update
    @yahoopost = Yahoopost.find(params[:id])

    respond_to do |format|
      if @yahoopost.update_attributes(params[:yahoopost])
        format.html { redirect_to(@yahoopost, :notice => 'Yahoopost was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @yahoopost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /yahooposts/1
  # DELETE /yahooposts/1.xml
  def destroy
    @yahoopost = Yahoopost.find(params[:id])
    @yahoopost.destroy

    respond_to do |format|
      format.html { redirect_to(yahooposts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/yahooposts_helper.rb
module YahoopostsHelper
end

app/views/yahooposts/_form.html.erb
<%= form_for(@yahoopost) do |f| %>
  <% if @yahoopost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yahoopost.errors.count, "error") %> prohibited this yahoopost from being saved:</h2>

      <ul>
      <% @yahoopost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/yahooposts/edit.html.erb
<h1>Editing yahoopost</h1>

<%= render 'form' %>

<%= link_to 'Show', @yahoopost %> |
<%= link_to 'Back', yahooposts_path %>

app/views/yahooposts/index.html.erb
<h1>Listing yahooposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @yahooposts.each do |yahoopost| %>
  <tr>
    <td><%= yahoopost.content %></td>
    <td><%= yahoopost.user_id %></td>
    <td><%= link_to 'Show', yahoopost %></td>
    <td><%= link_to 'Edit', edit_yahoopost_path(yahoopost) %></td>
    <td><%= link_to 'Destroy', yahoopost, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Yahoopost', new_yahoopost_path %>

app/views/yahooposts/new.html.erb
<h1>New yahoopost</h1>

<%= render 'form' %>

<%= link_to 'Back', yahooposts_path %>

app/views/yahooposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @yahoopost.content %>
</p>

<p>
  <b>User:</b>
  <%= @yahoopost.user_id %>
</p>


<%= link_to 'Edit', edit_yahoopost_path(@yahoopost) %> |
<%= link_to 'Back', yahooposts_path %>