config/routes.rb
MyDemo::Application.routes.draw do
  resources :randomtessses

  resources :yahooposts

  resources :sinaposts

  resources :microposts

  resources :users

  get "welcome/index"

  root :to => "welcome#index"

end

app/models/sinapost.rb
class Sinapost < ActiveRecord::Base
	belongs_to :user
	validate :content, :length => { :maximum => 40 }
end

app/controllers/sinaposts_controller.rb
class SinapostsController < ApplicationController
  # GET /sinaposts
  # GET /sinaposts.xml
  def index
    @sinaposts = Sinapost.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sinaposts }
    end
  end

  # GET /sinaposts/1
  # GET /sinaposts/1.xml
  def show
    @sinapost = Sinapost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sinapost }
    end
  end

  # GET /sinaposts/new
  # GET /sinaposts/new.xml
  def new
    @sinapost = Sinapost.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sinapost }
    end
  end

  # GET /sinaposts/1/edit
  def edit
    @sinapost = Sinapost.find(params[:id])
  end

  # POST /sinaposts
  # POST /sinaposts.xml
  def create
    @sinapost = Sinapost.new(params[:sinapost])

    respond_to do |format|
      if @sinapost.save
        format.html { redirect_to(@sinapost, :notice => 'Sinapost was successfully created.') }
        format.xml  { render :xml => @sinapost, :status => :created, :location => @sinapost }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sinapost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sinaposts/1
  # PUT /sinaposts/1.xml
  def update
    @sinapost = Sinapost.find(params[:id])

    respond_to do |format|
      if @sinapost.update_attributes(params[:sinapost])
        format.html { redirect_to(@sinapost, :notice => 'Sinapost was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sinapost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sinaposts/1
  # DELETE /sinaposts/1.xml
  def destroy
    @sinapost = Sinapost.find(params[:id])
    @sinapost.destroy

    respond_to do |format|
      format.html { redirect_to(sinaposts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sinaposts_helper.rb
module SinapostsHelper
end

app/views/sinaposts/_form.html.erb
<%= form_for(@sinapost) do |f| %>
  <% if @sinapost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sinapost.errors.count, "error") %> prohibited this sinapost from being saved:</h2>

      <ul>
      <% @sinapost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sinaposts/edit.html.erb
<h1>Editing sinapost</h1>

<%= render 'form' %>

<%= link_to 'Show', @sinapost %> |
<%= link_to 'Back', sinaposts_path %>

app/views/sinaposts/index.html.erb
<h1>Listing sinaposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sinaposts.each do |sinapost| %>
  <tr>
    <td><%= sinapost.content %></td>
    <td><%= sinapost.user_id %></td>
    <td><%= link_to 'Show', sinapost %></td>
    <td><%= link_to 'Edit', edit_sinapost_path(sinapost) %></td>
    <td><%= link_to 'Destroy', sinapost, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sinapost', new_sinapost_path %>

app/views/sinaposts/new.html.erb
<h1>New sinapost</h1>

<%= render 'form' %>

<%= link_to 'Back', sinaposts_path %>

app/views/sinaposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @sinapost.content %>
</p>

<p>
  <b>User:</b>
  <%= @sinapost.user_id %>
</p>


<%= link_to 'Edit', edit_sinapost_path(@sinapost) %> |
<%= link_to 'Back', sinaposts_path %>