config/routes.rb
MyDemo::Application.routes.draw do
  resources :randomtessses

  resources :yahooposts

  resources :sinaposts

  resources :microposts

  resources :users

  get "welcome/index"

  root :to => "welcome#index"

end

app/controllers/randomtessses_controller.rb
class RandomtesssesController < ApplicationController
  # GET /randomtessses
  # GET /randomtessses.xml
  def index
    @randomtessses = Randomtesss.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @randomtessses }
    end
  end

  # GET /randomtessses/1
  # GET /randomtessses/1.xml
  def show
    @randomtesss = Randomtesss.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @randomtesss }
    end
  end

  # GET /randomtessses/new
  # GET /randomtessses/new.xml
  def new
    @randomtesss = Randomtesss.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @randomtesss }
    end
  end

  # GET /randomtessses/1/edit
  def edit
    @randomtesss = Randomtesss.find(params[:id])
  end

  # POST /randomtessses
  # POST /randomtessses.xml
  def create
    @randomtesss = Randomtesss.new(params[:randomtesss])

    respond_to do |format|
      if @randomtesss.save
        format.html { redirect_to(@randomtesss, :notice => 'Randomtesss was successfully created.') }
        format.xml  { render :xml => @randomtesss, :status => :created, :location => @randomtesss }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @randomtesss.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /randomtessses/1
  # PUT /randomtessses/1.xml
  def update
    @randomtesss = Randomtesss.find(params[:id])

    respond_to do |format|
      if @randomtesss.update_attributes(params[:randomtesss])
        format.html { redirect_to(@randomtesss, :notice => 'Randomtesss was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @randomtesss.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /randomtessses/1
  # DELETE /randomtessses/1.xml
  def destroy
    @randomtesss = Randomtesss.find(params[:id])
    @randomtesss.destroy

    respond_to do |format|
      format.html { redirect_to(randomtessses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/randomtessses_helper.rb
module RandomtesssesHelper
end

app/views/randomtessses/_form.html.erb
<%= form_for(@randomtesss) do |f| %>
  <% if @randomtesss.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@randomtesss.errors.count, "error") %> prohibited this randomtesss from being saved:</h2>

      <ul>
      <% @randomtesss.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/randomtessses/edit.html.erb
<h1>Editing randomtesss</h1>

<%= render 'form' %>

<%= link_to 'Show', @randomtesss %> |
<%= link_to 'Back', randomtessses_path %>

app/views/randomtessses/index.html.erb
<h1>Listing randomtessses</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @randomtessses.each do |randomtesss| %>
  <tr>
    <td><%= randomtesss.content %></td>
    <td><%= randomtesss.user_id %></td>
    <td><%= link_to 'Show', randomtesss %></td>
    <td><%= link_to 'Edit', edit_randomtesss_path(randomtesss) %></td>
    <td><%= link_to 'Destroy', randomtesss, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Randomtesss', new_randomtesss_path %>

app/views/randomtessses/new.html.erb
<h1>New randomtesss</h1>

<%= render 'form' %>

<%= link_to 'Back', randomtessses_path %>

app/views/randomtessses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @randomtesss.content %>
</p>

<p>
  <b>User:</b>
  <%= @randomtesss.user_id %>
</p>


<%= link_to 'Edit', edit_randomtesss_path(@randomtesss) %> |
<%= link_to 'Back', randomtessses_path %>